version: '3.8'

services:
  nginx:
    build: ./requirements/nginx
    container_name: nginx
    ports:
      - "443:443"
    restart: always
    networks:
      - inception_network

networks:
  inception_network:
    driver: bridge
