
services:
  nginx:
    build: ./requirements/nginx
    container_name: nginx
    ports:
      - "8443:443"
    # ports:
    #   - "443:443"
    restart: always
    volumes:
      - wp_files:/var/www/html
    networks:
      - inception_network
  wordpress:
    build: ./requirements/wordpress
    container_name: wordpress
    restart: always
    volumes:
      - wp_files:/var/www/html
    env_file:
      - .env
    depends_on:
      - mariadb
    networks:
      - inception_network
  mariadb:
    build: ./requirements/mariadb
    container_name: mariadb
    restart: always
    volumes:
      - mariadb_data:/var/lib/mysql
    env_file:
      - ./.env
    networks:
      - inception_network
volumes:
  wp_files:
  mariadb_data:

networks:
  inception_network:
    driver: bridge
