services:
  nginx:
    build: ./requirements/nginx
    container_name: nginx
    image: nginx
    ports:
      - "443:443"
    restart: always
    volumes:
      - /home/falberti/data/wp_files:/var/www/html
    depends_on:
      - wordpress
    networks:
      - inception_network

  wordpress:
    build: ./requirements/wordpress
    container_name: wordpress
    image: wordpress
    restart: always
    volumes:
      - /home/falberti/data/wp_files:/var/www/html
    env_file:
      - .env
    depends_on:
      - mariadb
    networks:
      - inception_network

  mariadb:
    build: ./requirements/mariadb
    container_name: mariadb
    image: mariadb
    restart: always
    volumes:
      - /home/falberti/data/mariadb_data:/var/lib/mysql
    env_file:
      - .env
    networks:
      - inception_network

volumes:
  wp_files:
  mariadb_data:

networks:
  inception_network:
    driver: bridge
